# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Judge it!' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Judge it!

pod 'Google/SignIn'
    pod 'Google/AdMob'
    pod 'Google/CloudMessaging'
    pod 'Google/Analytics'
    pod 'OAStackView'
    pod 'TTTAttributedLabel'
    pod 'libPhoneNumber-iOS', '~> 0.9.2'
    pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v4.11.0'
    pod 'IQKeyboardManagerSwift', '~> 4.0.8' #swift3ready
    pod 'KMPlaceholderTextView', '~> 1.3.0'
    pod 'Alamofire', '~> 4.2.0'
    pod 'SwiftyJSON', '3.1.3'
    pod 'SecureNSUserDefaults', '~> 1.0.1'
    pod 'NYTPhotoViewer', '~> 1.2.0'
    pod 'Charts', '~> 3.0.0'
    pod 'NSHash'
    pod 'AlamofireImage', '~> 3.2.0'
    pod 'FSCalendar’, ‘~> 2.6.0’
    pod 'OpalImagePicker’, ‘~> 1.2.0’
    pod 'BBBadgeBarButtonItem'
pod 'AlamofireNetworkActivityLogger', '~> 2.2’


  target 'Judge it!Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
